version: '3'
services:
  app:
    image: 'jlesage/nginx-proxy-manager'
    ports:
      - '80:8080'
      - '81:8181'
      - '443:4443'
    volumes:
      - ./config.json:/app/config/production.json
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  db:
    image: jlesage/nginx-proxy-manager
    environment:
      MYSQL_ROOT_PASSWORD: 'rsasr4882'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'roba'
      MYSQL_PASSWORD: 'rsasr4882'
    volumes:
      - ./data/mysql:/var/lib/mysql